### ISSUE TITLE
[DevSecOps] GitLab & Jenkins CI/CD on Amazon EKS 🎯🚀🌥️

### ISSUE THREAD

**Issue by nnthanh101** [nnthanh101/cdk#6]
**PART 1. Provisioning Amazon S3, VPC, EFS, EKS cluster using `Terraform` or `CDK` Infrastructure as Code IaC** 👌💪

* [x] 1.1. **VPC**

* [x] 1.2. Amazon **S3**

* [x] 1.3. **EFS**

* [x] 1.4. **VPC Endpoints**
  * [x] 1.4.1. VPC Endpoint: `vpc.add_s3_endpoint("VPC Endpoints for S3")`
  * [ ] 1.4.2. [Interface VPC Endpoints in Amazon EFS](https://docs.aws.amazon.com/efs/latest/ug/efs-vpc-endpoints.html)

* [x] 1.5. **EKS cluster**: 
  * [x] 1.5.1. Classic Node Group
  * [ ] 1.5.2. Managed Node Group

* [ ] 1.6. [Building for Cost Optimization and Resilience for EKS with Spot Instances](https://aws.amazon.com/blogs/compute/cost-optimization-and-resilience-eks-with-spot-instances/)
  * [x] 1.6.1. Node Terminate Handler 
  * [ ] 1.6.2. EC2 Spot Instances

* [x] 1.7.1. **NLB** / **ACM** / **Route53**
* [x] 1.7.2. **ALB** / **ACM** / **Route53**

**PART 2. DevSecOps on Amazon EKS**

* [x] 2.1. Metric Server: HPA & CA Auto-Scaling

* [x] 2.2. CloudWatch >> Container Insights

* [x] 2.3. EKS Cluster includes both **EKS Managed Node Group** & **EKS Classic Node Group** - shared the same **NLB**: [Gitlab on EKS](http://gitlab.aws.job4u.io) and [Jenkins on EKS](http://jenkins.aws.job4u.io

* [ ] GitLab Runner registration: Amazon EKS cluster using Helm chart.
  * [ ] Gitlab: normal + Classic-NG + Private Subnet
  * [ ] Gitlab-Runner: spot + Classic-NG + Private Subnet
  * [ ] Vue.js: spot + Managed-NG + Public Subnet

* [ ] Jenkins: using Helm chart.

* [ ] **EKS Managed Node Group**
  * [ ] 8.1.1. GitLab Repository > *-ondemand
  * [ ] 8.2.1. Jenkins Master > *-ondemand

* [ ] **EKS Classic Node Group**   
  * [ ] 8.1.2. GitLab-Runner: *-spot 
  * [ ] 8.2.2. Jenkins Agents: *-spot

**PART 3. GitLab CI/CD on Amazon EKS as DevOps CI/CD Pipeline**

* [ ] `.gitlab-ci.yml`
  * [ ] Tells the GitLab Runner what to do
  * [ ] Defines stages of the pipeline – build, compile, test, deploy

* [ ] Docker image to run the pipeline stages
  * [ ] Using sample **Node.js** image with a demo application
  * [ ] Using sample **Go** image with a demo application
  * [ ] Using sample **Vue.js** image with a demo application

## References

* [ ] https://docs.gitlab.com/runner/install/kubernetes.html
* [ ] https://docs.gitlab.com/ee/ci/quick_start/
* [ ] https://docs.gitlab.com/ee/ci/yaml/

* [ ] 1. An **EKS cluster** created

* [ ] 2. **Gitlab Runner** registration: Amazon EKS cluster using helm chart

* [ ] 2. **.gitlab-ci.yml** 
  * [ ] Tells the GitLab Runner what to do
  * [ ] Defines stages of the pipeline – build, compile, test, deploy

* [ ] Docker image to run the pipeline stages
  * [ ] Using sample **Java SpringBoot** image with a demo application
  * [ ] Using sample **.NET Core** image with a demo application

## References

* [ ] https://docs.gitlab.com/runner/install/kubernetes.html
* [ ] https://docs.gitlab.com/ee/ci/quick_start/
* [ ] https://docs.gitlab.com/ee/ci/yaml/

**Comment by nnthanh101** [comment]
As an Organization looking to innovate and secure your Software Development initiatives, all paths lead to DevSecOps.

1. **Infrastructure as Code** using `Terraform` or `CDK`: treat Infrastructure the same way Developer treats the Code with all best practices and tests. AWS provides DevOps focused way of creating and maintaining infrastructure.

1. **Continuous Deployment**: core concept of a DevOps strategy. Its primary goal is to enable the automated deployment of production-ready application code.

1. **Automation**: focuses on setup, configuration, deployment, and support of infrastructure and applications.

1. **Monitoring**: communication and collaboration is fundamental in a DevOps strategy. To facilitate this, feedback is critical.

1. **Security**: focus on security is still of paramount importance. Infrastructure and company assets need to be protected, and when issues arises, they need to be rapidly and effectively addressed.

**Comment by nnthanh101** [comment]
Closed
